# Generated by Django 2.2.7 on 2020-08-25 20:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import wga.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_fact', models.CharField(max_length=1024)),
                ('target_fact', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.CharField(blank=True, max_length=20, null=True)),
                ('rule_antecedent', models.CharField(default='__________', max_length=1024)),
                ('rule_consequent', models.CharField(default='__________', max_length=1024)),
                ('context', models.CharField(default='Create Rule', max_length=64)),
                ('context_data', models.CharField(blank=True, max_length=1024)),
                ('turn', models.IntegerField(choices=[(0, 'Critic'), (1, 'Advocate'), (2, 'Moderated'), (3, 'Completed'), (4, 'Conversation')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('case', models.CharField(choices=[('Control', 'Control'), ('Non-control', 'Non-control')], max_length=64)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start', models.DateTimeField()),
                ('num_users', models.IntegerField()),
                ('num_games', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('key', models.CharField(default=wga.models.create_key, max_length=20, unique=True)),
                ('log_in', models.DateTimeField(blank=True, null=True)),
                ('assigned', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wga.Group')),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('source_conclusion', models.CharField(max_length=1024)),
                ('target_conclusion', models.CharField(max_length=1024)),
                ('facts', models.ManyToManyField(to='wga.FactPair')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.CharField(max_length=1024)),
                ('note', models.CharField(max_length=1024, null=True)),
                ('returned', models.IntegerField(choices=[(0, 'Critic'), (1, 'Advocate'), (3, 'End Game')], null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wga.Game')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wga.User')),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.CharField(max_length=64)),
                ('text', models.CharField(max_length=1024)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wga.Game')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wga.User')),
            ],
        ),
        migrations.CreateModel(
            name='Intermediary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=wga.models.create_key, max_length=20, unique=True)),
                ('role', models.CharField(choices=[('Advocate', 'Advocate'), ('Critic', 'Critic'), ('Interlocutor', 'Interlocutor')], max_length=64)),
                ('time', models.FloatField(default=0.0)),
                ('messages', models.ManyToManyField(to='wga.Message')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wga.User')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='messages',
            field=models.ManyToManyField(to='wga.Message'),
        ),
        migrations.AddField(
            model_name='group',
            name='scenarios',
            field=models.ManyToManyField(to='wga.ScenarioPair'),
        ),
        migrations.AddField(
            model_name='game',
            name='adv_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advocacy', to='wga.Intermediary'),
        ),
        migrations.AddField(
            model_name='game',
            name='crt_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criticism', to='wga.Intermediary'),
        ),
        migrations.AddField(
            model_name='game',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wga.Group'),
        ),
        migrations.AddField(
            model_name='game',
            name='scenario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wga.ScenarioPair'),
        ),
        migrations.AddField(
            model_name='factpair',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wga.Game'),
        ),
    ]
